closes #4
Luckytama/Empire pull request #19
Opened 2018-04-13 10:05 UTC by Alesfatalis

2018-04-13 11:23 UTC, Luckytama requested changes

2018-04-13 11:23 UTC, Luckytama commented on src/main/scala/de/htwg/se/empire/model/player/Player.scala
> +  def addCountry(country: Country): Unit = {
kann vereinfacht werden ->
def addCountry(country: Country): Unit = contries.append(country)

2018-04-13 11:23 UTC, Luckytama commented on src/main/scala/de/htwg/se/empire/model/player/Player.scala
> +  override def toString: String = name
erweitern mit besitzenden Ländern

2018-04-13 11:23 UTC, Luckytama commented on src/test/scala/de/htwg/se/empire/model/player/PlayerTest.scala
> +    val countries = ListBuffer[Country](Country("Another Country", null))
[Country] can be removed

2018-04-13 11:23 UTC, Luckytama commented on src/test/scala/de/htwg/se/empire/model/player/PlayerTest.scala
> +      "have an country" in {
typo

2018-04-18 23:59 UTC, Alesfatalis commented
All changes made. Can now be merged.

2018-04-19 09:03 UTC, Luckytama requested changes
@Alesfatalis nearly merged

2018-04-19 09:03 UTC, Luckytama commented on src/main/scala/de/htwg/se/empire/model/player/Player.scala
> +case class Player(name: String, countries: ListBuffer[Country]) {
Wenn ich darüber nachdenke würde ich fast sagen, dass ein Player die countries in einer lokalen Variable gespeichert haben sollte und nicht im Konstruktor.
- Spieler wird initial ja noch ohne Countries angelegt. Die werden erst vom Controller beim Spielstart zufällig vergeben

2018-04-19 09:03 UTC, Luckytama commented on src/main/scala/de/htwg/se/empire/model/player/Player.scala
> +  def getCountryAmount(): Int = countries.size
Klammern können weggelassen werden

2018-04-25 14:49 UTC, Luckytama approved these changes

2018-04-25 14:57 UTC, merged