Implement Country Model + Test
Luckytama/Empire pull request #9
Opened 2018-03-14 13:22 UTC by Luckytama

2018-03-15 12:30 UTC, Luckytama commented
connects to #6

2018-03-28 12:18 UTC, Luckytama commented
closes #6

2018-03-28 12:25 UTC, Alesfatalis requested changes

2018-03-28 12:25 UTC, Alesfatalis commented on src/main/scala/de/htwg/se/empire/model/grid/Country.scala
> +
Hier sollte noch die `removeSoldiers` Funktion hin. Damit im Falle eines Angriffs Soldaten wieder entfernt werden können.

2018-03-28 12:25 UTC, Alesfatalis commented on src/test/scala/de/htwg/se/empire/model/grid/CountryTest.scala
> +      }
Test für `removeSoldiers` implementieren.

2018-04-04 08:18 UTC, Luckytama commented
![Alt Text](https://media.giphy.com/media/tXL4FHPSnVJ0A/giphy.gif)

2018-04-05 06:29 UTC, Luckytama commented
![Alt Text](https://media.giphy.com/media/o5oLImoQgGsKY/giphy.gif)

2018-04-05 12:02 UTC, Alesfatalis approved these changes
Passt

2018-04-05 12:02 UTC, Alesfatalis commented
Konflikte löse ich noch auf.

2018-04-05 12:10 UTC, Luckytama commented
@Alesfatalis nene Konflikte und mergen macht immer der der den Pull Request erstellt hat

2018-04-05 13:05 UTC, merged